name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: .python-version
    - name: Install uv
      uses: astral-sh/setup-uv@v3
    #- name: Check code formatting
    #  run: uv run ruff check
    #- name: Check Python types
    #  run: uv run mypy
    - name: Run tests
      run: uv run pytest
