name: Package and release

on:
  release:
    types: [published]

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Python
      uses: actions/setup-python@v5
      with:
        python-version-file: .python-version

    - name: Install uv
      uses: astral-sh/setup-uv@v3

    - name: Build
      run: uv build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: release-dists
        path: dist/
        if-no-files-found: error

  pypi-publish:
    needs:
    - release-build
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment:
      name: pypi
      url: https://pypi.org/p/snuffkin-playground

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: release-dists
        path: dist/

    - name: Publish release distributions to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        packages-dir: dist/
